---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: slider
  label: Slider
  create: documents
  match: "**/*"
  templates:
  - slider
- type: directory
  path: explore
  label: Explore
  create: documents
  match: "**/*"
  templates:
  - explore
- type: directory
  path: journal
  label: Journal
  create: documents
  match: "**/*.md"
  templates:
  - journal
- type: document
  path: data/theme.json
  label: Theme config
upload_dir: chrinas
public_path: https://res.cloudinary.com/skrypt/image/upload
front_matter_path: https://res.cloudinary.com/skrypt/image/upload/c_limit,w_1240,dpr_auto,f_auto
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
